print("Give me a noun")
noun = input()
print("Give me an verb")
verb = input ()
print("Give me an adjective")
adjective = input()
print(f"The {noun} was {adjective} when it {verb} to school")
print("Give me a noun")
noun = input()
print("Give me an verb")
verb = input()
print("Give me an adjective")
adjective = input()
print(f"The {noun} was {adjective} when it {verb} to school")