print("Give me a noun")
noun = input()
print("Give me an adverb")
adverb = input ()
print("Give me an adjective")
adjective = input()
print(f"The {noun} was {adjective} when it {adverb} went to school")
print("Give me a noun")
noun = input()
print("Give me an adverb")
adverb = input()
print("Give me an adjective")
adjective = input()
print(f"The {noun} was {adjective} when it {adverb} went to school")